name: Generate Output

on:
  workflow_call:
    outputs:
      output:
        description: 'Generated output'
        value: ${{ steps.generate.outputs.result }}

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - id: generate
        run: echo "result=hello-world" >> "$GITHUB_OUTPUT"
