name: Use Output

on:
  workflow_call:
    inputs:
      input:
        required: true
        type: string

jobs:
  use:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Input
        run: echo "Using input: ${{ inputs.input }}"
